title: "John Spencer Terry"
google_analytics: G-KCKCJBP62T
permalink: pretty
collections:
  writing:
    output: true
    permalink: /writing/:path/
  food:
    output: true
    permalink: /food/:path/
